#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/22053098/clone ensure=absent force=true
puppet resource file /tmp ensure=directory
puppet resource file /tmp/22053098 ensure=directory
puppet resource file /tmp/22053098/clone ensure=directory
cd /tmp/22053098/clone
git clone https://github.com/VincentSey/22053098_repo.git
cp -p /tmp/22053098/clone/22053098_repo/22053098_index.html /var/www/html
